// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {parser} from '../models';

export function BrowseDir(arg1:string):Promise<string>;

export function ParseDir(arg1:string):Promise<Array<parser.Trainer>>;

export function ParseFile(arg1:string):Promise<parser.Trainer>;

export function ResolveTitleName(arg1:string):Promise<string>;
