// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseDir(arg1) {
  return window['go']['app']['App']['BrowseDir'](arg1);
}

export function ParseDir(arg1) {
  return window['go']['app']['App']['ParseDir'](arg1);
}

export function ParseFile(arg1) {
  return window['go']['app']['App']['ParseFile'](arg1);
}

export function ResolveTitleName(arg1) {
  return window['go']['app']['App']['ResolveTitleName'](arg1);
}
